sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mchoi2000/exercise-logs-react .

script:
  - docker run -e CI=true mchoi2000/exercise-logs-react npm run test