# Specify base image
FROM node:alpine

# Add a user working space
WORKDIR /app

# Install dependencies
COPY package.json .
RUN npm install
COPY . .

# Run default command
# CMD ["npm", "run", "dev"]

# Run test
CMD ["npm", "run", "test"]
